/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Hand-written integration tests for com.microsoft contrib operators.
// Unlike tests/onnx_ops/, this file is NOT regenerated by
// scripts/generate_rust_op_conversion_tests.py.

// The shared runner also exposes expectation variants only the generated
// suite constructs.
#[allow(dead_code)]
mod common;

use common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::{ModelProto, OperatorSetIdProto};

fn with_ms_domain(mut model: ModelProto, ms_version: i64) -> ModelProto {
    model.opset_import.push(OperatorSetIdProto {
        domain: "com.microsoft".to_string(),
        version: ms_version,
    });
    model
}

/// MatMulBnb4 with the NF4 codebook: A[2,16] x dequant(B)[16,4].
/// The runner dispatches the converted WebNN graph and compares against ORT,
/// which validates the codebook values and the high/low nibble packing order.
fn build_matmul_bnb4(quant_type: i64) -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (k, n, block_size) = (16i64, 4i64, 16i64);
    let total = (k * n) as usize;
    // All 16 codes appear, exercising the whole codebook.
    let packed: Vec<u8> = (0..total / 2)
        .map(|i| ((i % 16) as u8) << 4 | ((15 - i % 16) as u8))
        .collect();
    let absmax: Vec<f32> = vec![0.5, 1.25, 2.0, 0.75];

    let mut node = node(
        "MatMulBnb4",
        "test_matmul_bnb4",
        &["A", "B", "absmax"],
        &["Y"],
        &[
            attr_int("K", k),
            attr_int("N", n),
            attr_int("block_size", block_size),
            attr_int("quant_type", quant_type),
        ],
    );
    node.domain = "com.microsoft".to_string();

    let model = model(
        17,
        graph(
            "test_MatMulBnb4_graph",
            vec![f32_input("A", &[2, k])],
            vec![f32_output("Y", &[2, n])],
            vec![node],
            vec![
                u8_init("B", &[(total / 2) as i64], &packed),
                f32_init("absmax", &[(total as i64) / block_size], &absmax),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

/// GroupQueryAttention with grouped KV heads (H=2, kvH=1) and a non-empty
/// KV cache (P=2, S=4). `seqlens_k`/`total_sequence_length` are constant
/// initializers set to the unpadded values the static lowering assumes, so
/// ORT computes the same attention pattern the WebNN causal mask encodes.
fn build_gqa() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (num_heads, kv_heads, head_dim) = (2i64, 1i64, 8i64);
    let (seq, past_seq) = (4i64, 2i64);
    let total_seq = seq + past_seq;

    let mut gqa = node(
        "GroupQueryAttention",
        "test_gqa",
        &[
            "query",
            "key",
            "value",
            "past_key",
            "past_value",
            "seqlens_k",
            "total_seq_len",
        ],
        &["Y", "present_key", "present_value"],
        &[
            attr_int("num_heads", num_heads),
            attr_int("kv_num_heads", kv_heads),
        ],
    );
    gqa.domain = "com.microsoft".to_string();

    let model = model(
        17,
        graph(
            "test_GroupQueryAttention_graph",
            vec![
                f32_input("query", &[1, seq, num_heads * head_dim]),
                f32_input("key", &[1, seq, kv_heads * head_dim]),
                f32_input("value", &[1, seq, kv_heads * head_dim]),
                f32_input("past_key", &[1, kv_heads, past_seq, head_dim]),
                f32_input("past_value", &[1, kv_heads, past_seq, head_dim]),
            ],
            vec![
                f32_output("Y", &[1, seq, num_heads * head_dim]),
                f32_output("present_key", &[1, kv_heads, total_seq, head_dim]),
                f32_output("present_value", &[1, kv_heads, total_seq, head_dim]),
            ],
            vec![gqa],
            vec![
                i32_init("seqlens_k", &[1], &[(total_seq - 1) as i32]),
                i32_init("total_seq_len", &[1], &[total_seq as i32]),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

#[test]
fn group_query_attention_matches_ort() {
    assert_op_matches_ort(build_gqa(), ExpectConvertOp::Success, 17);
}

#[test]
fn matmul_bnb4_nf4_matches_ort() {
    assert_op_matches_ort(build_matmul_bnb4(1), ExpectConvertOp::Success, 17);
}

#[test]
fn matmul_bnb4_fp4_matches_ort() {
    assert_op_matches_ort(build_matmul_bnb4(0), ExpectConvertOp::Success, 17);
}
