/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Hand-written integration tests for ai.onnx patterns that the generic
// per-op fixtures in tests/onnx_ops/ do not cover: torch.export (dynamo)
// shape idioms and attribute combinations that need a decomposition.
// Unlike tests/onnx_ops/, this file is NOT regenerated by
// scripts/generate_rust_op_conversion_tests.py.

#[allow(dead_code)]
mod common;

use common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

/// `Shape(x, start=-2)` feeds `ConstantOfShape`; the broadcast Add only
/// matches ORT if the sliced shape vector is `[4, 5]` rather than the full
/// `[2, 3, 4, 5]`.
fn build_shape_start_end() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        17,
        graph(
            "test_ShapeStartEnd_graph",
            vec![f32_input("x", &[2, 3, 4, 5])],
            vec![f32_output("y", &[2, 3, 4, 5])],
            vec![
                node(
                    "Shape",
                    "shape_tail",
                    &["x"],
                    &["tail"],
                    &[attr_int("start", -2)],
                ),
                node("ConstantOfShape", "zeros", &["tail"], &["z"], &[]),
                node("Add", "add", &["x", "z"], &["y"], &[]),
            ],
            vec![],
        ),
    )
}

/// dynamo `torch.arange(0.5, n, 1.0)`: a float Range whose limit is a Cast
/// of a sliced Shape. The result is added to the input so ORT checks the
/// generated values, not just the length.
fn build_float_range() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        17,
        graph(
            "test_FloatRange_graph",
            vec![f32_input("x", &[1, 14])],
            vec![f32_output("y", &[1, 14])],
            vec![
                node(
                    "Shape",
                    "shape_n",
                    &["x"],
                    &["n_vec"],
                    &[attr_int("start", 1), attr_int("end", 2)],
                ),
                node("Squeeze", "squeeze_n", &["n_vec", "zero_axis"], &["n"], &[]),
                node("Cast", "cast_n", &["n"], &["n_f"], &[attr_int("to", 1)]),
                node("Range", "arange", &["start", "n_f", "delta"], &["r"], &[]),
                node("Add", "add", &["x", "r"], &["y"], &[]),
            ],
            vec![
                i64_init("zero_axis", &[1], &[0]),
                f32_init("start", &[], &[0.5]),
                f32_init("delta", &[], &[1.0]),
            ],
        ),
    )
}

/// `torch.stack([a, b], dim=-1)` as exported by dynamo: opset-13 Unsqueeze
/// with a negative axes input on both operands, then Concat(axis=-1).
fn build_unsqueeze_stack() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        17,
        graph(
            "test_UnsqueezeStack_graph",
            vec![f32_input("x", &[4, 4])],
            vec![f32_output("y", &[4, 4, 2])],
            vec![
                node("Mul", "double", &["x", "two"], &["x2"], &[]),
                node("Unsqueeze", "unsq_a", &["x", "neg_one"], &["a"], &[]),
                node("Unsqueeze", "unsq_b", &["x2", "neg_one"], &["b"], &[]),
                node(
                    "Concat",
                    "stack",
                    &["a", "b"],
                    &["y"],
                    &[attr_int("axis", -1)],
                ),
            ],
            vec![
                f32_init("two", &[], &[2.0]),
                i64_init("neg_one", &[1], &[-1]),
            ],
        ),
    )
}

/// `AveragePool(count_include_pad=1)` with explicit padding: WebNN never
/// counts padding, so the conversion pads with zeros and pools unpadded.
fn build_average_pool_count_include_pad(kernel: &[i64], pads: &[i64]) -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let rank = kernel.len();
    let spatial: Vec<i64> = if rank == 1 { vec![6] } else { vec![4, 5] };
    let mut in_shape = vec![1, 2];
    in_shape.extend(&spatial);
    // stride 1, floor rounding: out = in + pad_begin + pad_end - kernel + 1
    let mut out_shape = vec![1, 2];
    for i in 0..rank {
        out_shape.push(spatial[i] + pads[i] + pads[i + rank] - kernel[i] + 1);
    }

    model(
        17,
        graph(
            "test_AveragePoolCountIncludePad_graph",
            vec![f32_input("x", &in_shape)],
            vec![f32_output("y", &out_shape)],
            vec![node(
                "AveragePool",
                "avg_pool",
                &["x"],
                &["y"],
                &[
                    attr_ints("kernel_shape", kernel),
                    attr_ints("pads", pads),
                    attr_int("count_include_pad", 1),
                ],
            )],
            vec![],
        ),
    )
}

#[test]
fn shape_start_end_matches_ort() {
    assert_op_matches_ort(build_shape_start_end(), ExpectConvertOp::Success, 17);
}

#[test]
fn float_range_matches_ort() {
    assert_op_matches_ort(build_float_range(), ExpectConvertOp::Success, 17);
}

#[test]
fn unsqueeze_negative_axes_stack_matches_ort() {
    assert_op_matches_ort(build_unsqueeze_stack(), ExpectConvertOp::Success, 17);
}

#[test]
fn average_pool_count_include_pad_2d_matches_ort() {
    assert_op_matches_ort(
        build_average_pool_count_include_pad(&[3, 3], &[1, 1, 1, 1]),
        ExpectConvertOp::Success,
        17,
    );
}

#[test]
fn average_pool_count_include_pad_asymmetric_matches_ort() {
    assert_op_matches_ort(
        build_average_pool_count_include_pad(&[2, 3], &[1, 0, 0, 2]),
        ExpectConvertOp::Success,
        17,
    );
}

#[test]
fn average_pool_count_include_pad_1d_matches_ort() {
    assert_op_matches_ort(
        build_average_pool_count_include_pad(&[3], &[1, 1]),
        ExpectConvertOp::Success,
        17,
    );
}
